#!/bin/bash

# Save trace setting
XTRACE=$(set +o | grep xtrace)
set +o xtrace

OMNI_DATA_DIR="/opt/stack/omni"
DIST_PACKAGES="/usr/local/lib/python2.7/dist-packages"
ENTRY_POINT="$DIST_PACKAGES/glance_store-*.dist-info/entry_points.txt"
NEUTRON_ENTRY_POINT="/opt/stack/neutron/neutron.egg-info/entry_points.txt"
# Functions
# ------------

function configure_omni_glance {
    sudo cp /etc/omni.json /etc/glance/
    iniset $GLANCE_API_CONF DEFAULT show_multiple_locations True
    iniset $GLANCE_API_CONF glance_store default_store gce
    iniset $GLANCE_API_CONF glance_store stores gce
    iniset $GLANCE_API_CONF GCE service_key_path /etc/glance/omni.json
    iniset $GLANCE_API_CONF GCE zone us-central1-c
    iniset $GLANCE_API_CONF GCE project_id omni-163105
    sudo crudini --set $ENTRY_POINT glance_store.drivers glance.store.gce.Store glance_store._drivers.gce:Store
    sudo crudini --set $ENTRY_POINT glance_store.drivers gce glance_store._drivers.gce:Store
    sudo sed -i -e "s/, 'vsphere')/, 'vsphere', 'gce')/g" $DIST_PACKAGES/glance_store/backend.py
    sudo cp $OMNI_DATA_DIR/glance/gce/gceutils.py /usr/local/lib/python2.7/dist-packages/glance_store/_drivers/
    sudo cp $OMNI_DATA_DIR/glance/glance_store/_drivers/gce.py /usr/local/lib/python2.7/dist-packages/glance_store/_drivers/
    sudo systemctl restart devstack@g-api.service devstack@g-reg.service
}

function configure_omni_neutron {
    sudo cp /etc/omni.json /etc/neutron/
    iniset $NEUTRON_CONF DEFAULT core_plugin ml2
    iniset $NEUTRON_CONF DEFAULT service_plugins neutron.services.l3_router.gce_router_plugin.GceRouterPlugin
    iniset $NEUTRON_CONF GCE service_key_path /etc/neutron/omni.json
    iniset $NEUTRON_CONF GCE zone us-central1-c
    iniset $NEUTRON_CONF GCE project_id omni-163105
    iniset $NEUTRON_CONF GCE region us-central1
    iniset $NEUTRON_CONF nova nova_region_name GCE
    iniset /etc/neutron/plugins/ml2/ml2_conf.ini ml2 type_drivers local,flat
    iniset /etc/neutron/plugins/ml2/ml2_conf.ini ml2 tenant_network_types local
    iniset /etc/neutron/plugins/ml2/ml2_conf.ini ml2_type_flat flat_networks '*'
    iniset /etc/neutron/plugins/ml2/ml2_conf.ini ml2_type_vlan network_vlan_ranges external
    iniset /etc/neutron/plugins/ml2/ml2_conf.ini ml2 mechanism_drivers gce
    sudo crudini --set $NEUTRON_ENTRY_POINT neutron.ml2.mechanism_drivers gce neutron.plugins.ml2.drivers.gce.mech_gce:GceMechanismDriver
    sudo crudini --set $NEUTRON_ENTRY_POINT neutron.service_plugins gce_router neutron.services.l3_router.gce_router_plugin:GceRouterPlugin
    sudo cp -R $OMNI_DATA_DIR/neutron/neutron/plugins/ml2/drivers/gce/ /opt/stack/neutron/neutron/plugins/ml2/drivers/
    sudo cp $OMNI_DATA_DIR/neutron/neutron/services/l3_router/gce_router_plugin.py /opt/stack/neutron/neutron/services/l3_router/
    sudo cp $OMNI_DATA_DIR/neutron/neutron/common/* /opt/stack/neutron/neutron/common/
    sudo systemctl restart devstack@q-agt.service devstack@q-dhcp.service devstack@q-l3.service devstack@q-meta.service devstack@q-svc.service
}

function configure_omni_nova {
    sudo cp /etc/omni.json /etc/nova/
    iniset $NOVA_CONF DEFAULT compute_driver gce.GCEDriver
    iniset $NOVA_CONF DEFAULT glance_api_insecure True
    iniset $NOVA_CONF DEFAULT cinder_api_insecure True
    iniset $NOVA_CONF DEFAULT vnc_enabled True
    iniset $NOVA_CONF DEFAULT sql_connection ""
    iniset $NOVA_CONF DEFAULT osapi_compute_extension nova.api.openstack.compute.contrib.standard_extensions
    iniset $NOVA_CONF DEFAULT force_dhcp_release True
    iniset $NOVA_CONF GCE service_key_path /etc/nova/omni.json
    iniset $NOVA_CONF GCE zone us-central1-c
    iniset $NOVA_CONF GCE project_id omni-163105
    sudo cp -R $OMNI_DATA_DIR/nova/virt/gce/ /opt/stack/nova/nova/virt/
    sudo systemctl restart devstack@n-api.service devstack@n-cauth.service devstack@n-cond.service devstack@n-cpu.service devstack@n-novnc.service devstack@n-sch.service
}

function configure_omni_cinder {
    sudo cp /etc/omni.json /etc/cinder/
    iniset $CINDER_CONF GCE service_key_path /etc/cinder/omni.json
    iniset $CINDER_CONF GCE zone us-central1-c
    iniset $CINDER_CONF GCE project_id omni-163105
    iniset $CINDER_CONF GCE region us-central1
    iniset $CINDER_CONF GCE gce_pool_name gce
    iniset $CINDER_CONF GCE gce_free_capacity_gb 2048
    iniset $CINDER_CONF gce_total_capacity_gb 2048
    iniset $CINDER_CONF GCE volume_driver cinder.volume.drivers.gce.driver.GceDriver
    iniset $CINDER_CONF DEFAULT enable_force_upload true
    iniset $CINDER_CONF DEFAULT enabled_backends GCE
    iniset $CINDER_CONF DEFAULT volumes_dir /etc/cinder/volumes
    iniset $CINDER_CONF DEFAULT os_privileged_user_name cinder
    iniset $CINDER_CONF DEFAULT default_volume_type GCE
    iniset $CINDER_CONF DEFAULT os_region_name GCE
    sudo cp -R $OMNI_DATA_DIR/cinder/volume/drivers/gce/ /opt/stack/cinder/cinder/volume/drivers/
    sudo systemctl restart devstack@c-sch.service devstack@c-vol.service devstack@c-api.service
}

# Restore xtrace
$XTRACE

## Local variables:
## mode: shell-script
## End: